const routeNames = {
  BASE_URL: "http://122.176.101.76:8081/api/",
  LOGIN: "/login",
  FORGOTPASSWORD: "/ForgotPassword",
  RESETPASSWORD: "/reset-password",
  DASHBOARD: "/",
  CASE: "/case",
  PASSWORDRESET: "/PasswordReset",
  CREATECASE: "/createcase",
  EDITCASE: "/case/edit",
  REQUESTER: "/requester",
  TERRITORY: "/territory",
  CREATEREQUESTER: "/createrequester",
  CREATETERRITORY: "/createterritory",
  INSPECTIONTYPE: "/inspectiontype",
  CREATEINSPECTIONTYPE: "/createinspectiontype",
  INSTALLATIONADDRESS: "/installationaddress",
  CREATEINSTALLATIONADDRESS: "/createinstallationaddress",
  SUBJECTTYPE: "/subjecttype",
  CREATESUBJECTTYPE: "/createsubjecttype",
  SUBJECT: "/subject",
  CREATETHESUBJECT: "/createthesubject",
  CREATEINSPECTION: "/inspection/create",
  EDITINSPECTION: "/inspection/edit",
  EDITTERRITORY: "/ territory/edit",
  INSPECTION: "/inspection",
  SPECIFICTOPIC: "/specifictopic",
  CREATESPECIFICTOPIC: "/createspecifictopic",
  EMPLOYEE: "/employee",
  CREATEEMPLOYEE: "/createemployee",
  CONTACT: "/contact",
  CREATECONTACT: "/createcontact",
  CASEMANAGER: "/casemanager",
  CREATECASEMANAGER: "/createcasemanager",
  CONTACT: "/contact",
  CREATECONTACT: "/createcontact",
  INSPECTIONCERTIFICATE: "/inspectioncertificate",
  REQUESTERDEPARTMENT: "/requesterdepartment",
  CREATEREQUESTERDEPARTMENT: "/createrequesterdepartment",
  USERMODULE: "/usermodule",
};
export default routeNames;
